version: 2
before:
  hooks:
    - make client-build
builds:
  - main: ./cmd/go-mail-admin
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X internal.version.Version={{ .Version }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-devel"