// Package openapiauth provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapiauth

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// CsrfResponse defines model for CsrfResponse.
type CsrfResponse struct {
	CsrfToken string `json:"csrfToken"`
}

// DashboardStatus defines model for DashboardStatus.
type DashboardStatus struct {
	Healthy bool `json:"healthy"`
}

// DashboardVersion defines model for DashboardVersion.
type DashboardVersion struct {
	Version string `json:"version"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Error   string `json:"error"`
	Message string `json:"message"`
}

// LoginParameter defines model for LoginParameter.
type LoginParameter struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Login bool   `json:"login"`
	Token string `json:"token"`
}

// UserOperationsLoginJSONRequestBody defines body for UserOperationsLogin for application/json ContentType.
type UserOperationsLoginJSONRequestBody = LoginParameter

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /csrf)
	UserOperationsCsrf(w http.ResponseWriter, r *http.Request)

	// (POST /login)
	UserOperationsLogin(w http.ResponseWriter, r *http.Request)

	// (GET /status)
	DashboardOperationsStatus(w http.ResponseWriter, r *http.Request)

	// (GET /version)
	DashboardOperationsVersion(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /csrf)
func (_ Unimplemented) UserOperationsCsrf(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /login)
func (_ Unimplemented) UserOperationsLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /status)
func (_ Unimplemented) DashboardOperationsStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /version)
func (_ Unimplemented) DashboardOperationsVersion(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// UserOperationsCsrf operation middleware
func (siw *ServerInterfaceWrapper) UserOperationsCsrf(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserOperationsCsrf(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UserOperationsLogin operation middleware
func (siw *ServerInterfaceWrapper) UserOperationsLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UserOperationsLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DashboardOperationsStatus operation middleware
func (siw *ServerInterfaceWrapper) DashboardOperationsStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DashboardOperationsStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DashboardOperationsVersion operation middleware
func (siw *ServerInterfaceWrapper) DashboardOperationsVersion(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DashboardOperationsVersion(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/csrf", wrapper.UserOperationsCsrf)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/login", wrapper.UserOperationsLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/status", wrapper.DashboardOperationsStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/version", wrapper.DashboardOperationsVersion)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xVTW/bOBD9K8LsHoXIm9x0y272UCBFgybtJfCBpsYSU4pkOaO0hqH/XpCyPmwriQsk",
	"PeQmDkczj+/NxxakrZ01aJgg3wLJCmsRP/8jv/6M5KwhDGfnrUPPCuOtJL++s9/QhANvHEIOxF6ZEto2",
	"BY/fG+WxgPx+4rpMe1e7ekDJ0KZwJahaWeGLWxbc0HGmCoXmajPJs7JWozBHiXrPZ9N8RU/KmuM8j+PF",
	"8+/pHefS/O+99TNs2SJyuLa+Fgw5KMMX5zAEUIaxRB8iYB/hAEQKNRKJEk8gPGQb/fuYc3ivbanMjfCi",
	"RsYZ4E4Q/bC+mAXUEHoj6hMQDZ7pGPFJOE8XnQ7Xc4WQAp9Wi12E3v0YQvBXZm1jJMU63H0USieXRa1M",
	"cov+UcnwjKFaYHG2OFsECNahEU5BDhfRFN7KVQSeCSltYxjybZsOp2yrinbGlE1Yj3daxZYcvqc/hu4K",
	"KUoM0QMIL1hZ86GAHL4Q+k+9hUJHQ+Cj4zciO18sugI1jBEfCOe0kvGP7IG6hujGQvj62+MacvgrG+dG",
	"thsa2d7EiFQWSNIrxx1TdxUmQQwkTipBCTVSIhZYnEWdWJQUNAqgIYWbZqWVhGW4ygpbiyj9eJiSMBSG",
	"s/QiDde7GthB+dcWm1ej4KCf2v36Y99g+4YC7LfPbyoQfNei0fxqcLphOAPj0iSNwZ8OJWORxOmU9KS8",
	"XAvalrbpW4lYME2+uw0y2wzDChhLYbdz3lCSw/X2HkQZ3nSoDGtyViu52QkynKe9Otmzp8rU7+w/oVOf",
	"6/0K1aZA6IMMkN9vofEacqiYXZ5l2kqhK0ucCaeyx3+gXQ7httAte7iK85egTQfTZbe+9m1hVeGe6W4o",
	"kIkx9vjkvEM6sYzvaJftrwAAAP//TASSdrMKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
